version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image : "gwilym/wurstmeister-kafka-docker"
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.37
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "device:state:set,Topic1:1:3,Topic2:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

