@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/java.puml
!include FONTAWESOME/users.puml

System_Boundary(device_manager, "Управление устройствами") {

	class MessageConsumer {
		+Command receive_message();
	}

	class Message {
		integer device_id
		string status
		float current_temperature
	}

	class Database {
		-Device[] devices
		+void process_message(String message)
		-bool add_device(Device new_device)
		-bool remove_device(int device_id)
	}

	class Device {
		-integer device_id
		+void update_state(String new_state)
	}

	Device -- Message : использование
	Device "*..1" o-- "1" Database : хранение
	MessageConsumer -- Message : получение
}

System_Boundary(telemetry_manager, "Телеметрия") {

	class Database {
		-Device[] devices
		+void process_message(String message)
		-bool add_device(Device new_device)
		-bool remove_device(int device_id)
	}

	class TelemetryData {
		+integer device_id
		+string data
		+ json()
	}

	class Device {
		-integer device_id
		+void update_state(String new_state)
	}

	class MessageProducer {
		+void send_message(TelemetryData)
	}

	Device -- TelemetryData : создание
	TelemetryData -- MessageProducer : отправка
	Device "*..1" o-- "1" Database : хранение
}


@enduml
